### ISSUE TITLE
[Question] is there a way to have a package.json for each apps and libs ? 

### ISSUE THREAD

**Issue by billyjov** [LayZeeDK/ngx-nrwl-airlines-workspace#2]
In order to enable independent deployment and easier dockerization of each app, it will be good to have a `package.json` in each  sub app and libs. Is there a way to archieve this ?

**Comment by LayZeeDK** [comment]
Hi Billy,

Can you explain the workflow you're looking for in a bit more detail?

**Comment by billyjov** [comment]
Yes!. 

I want to build a monorepo with multiple angular apps & libs (à la nx). my actual issue with nx is that there is no official solution on how to support multiple `package.json` inside each app or lib. All packages are actually located into the root `package.json`.

I would love to see every app having different `package.json` so that i can have apps with differents version of e.g Angular .

The main Goal is the ability to update & deploy one app without care about what the other apps does.

**Comment by LayZeeDK** [comment]
That goes against the philosophy of Nx and most monorepo approaches. You would be happier with Lerna https://lerna.js.org/

**Comment by billyjov** [comment]
Thanks. II thought I could archieve that with nx. But if it's definitly no so possible, i will take a look at lerna
